{{- if .Values.secrets.storage.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iterion.fullname" . }}-storage
  labels:
    {{- include "iterion.labels" . | nindent 4 }}
type: Opaque
stringData:
  ITERION_S3_ACCESS_KEY_ID: {{ .Values.secrets.storage.s3AccessKeyId | quote }}
  ITERION_S3_SECRET_ACCESS_KEY: {{ .Values.secrets.storage.s3SecretAccessKey | quote }}
{{- end -}}
