{{- if .Values.secrets.llm.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iterion.fullname" . }}-llm
  labels:
    {{- include "iterion.labels" . | nindent 4 }}
type: Opaque
stringData:
  ANTHROPIC_API_KEY: {{ .Values.secrets.llm.anthropicApiKey | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.llm.openaiApiKey | quote }}
{{- end -}}
